service: alphadump

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  profile: ${env:PROFILE}
  stage: ${env:STAGE, self:custom.stage}
  region: ${env:REGION, self:custom.region}
  deploymentBucket: alphadump-deployments
  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: arn:aws:s3:::${env:S3_BUCKET}

custom:
  stage: dev
  region: us-east-1

functions:
  default:
    handler: src/index.default
    description: Scheduled dump of the contents of a Postgres db into an S3 bucket.
    timeout: 300
    events:
      - schedule: rate(2 minutes) # cron(0 0 * * ? *) # 00:00 hrs every day
