#!/usr/local/bin/node
/* eslint-disable no-console */
const path = require("path");

let handler;
let eventJson = require(path.resolve("event.json"));

handler = require(path.resolve("build/src/index.js")).default;

if (!handler) {
  console.error("Missing default export in function file.");
  process.exit(1);
}

handler(eventJson, {
  succeed: (data) => {
    console.log(data);
    process.exit(0);
  },
  fail: (error) => {
    console.error(error);
    process.exit(1);
  }
}, (error, data) => {
  if (error) {
    console.error(error);
    process.exit(1);
  }

  console.log(data);
  process.exit(0);
});
